import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {RecipeService} from "@/app/service/recipe.service";
import {NEAPOLITAN, NY_STYLE, PAPA_JOHNS} from "@/app/static-data";
import {useMemo} from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    useMemo(() => {
       loadTestData();
    }, []);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

const loadTestData = () => {
    RecipeService.saveRootRecipe(NEAPOLITAN);
    RecipeService.saveRecipeNode(NY_STYLE);
    RecipeService.saveRecipeNode(PAPA_JOHNS);
}
